---
apiVersion: machine.openshift.io/v1beta1
kind: Machine
metadata:
  name: kubevirt-actuator-testing-machine8
  namespace: openshift-machine-api
  labels:
    # the namespace the vms will be created in
    machine.openshift.io/cluster-api-cluster: openshift-machine-api
#    machine.openshift.io/cluster-api-cluster: namespace-test
spec:
  metadata:
    labels:
      node-role.kubernetes.io/master: ""
      node-role.kubernetes.io/infra: ""
  providerSpec:
    value:
      # TODO: determine the version : apiVersion: kubevirtproviderconfig.openshift.io/v1beta1
      kind: KubevirtMachineProviderSpec
      SecretName: underkube-config
      SourcePvcName: pvc-rhcos-image
      RequestedMemory: "2048M"
      RequestedCPU: ""
      RequestedStorage: "35Gi",
      MachineType: ""
      StorageClassName: ""
      IgnitionSecretName: "worker-user-data"

